[build]
  # Forcing Netlify to ignore cache and rebuild
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_FORCE_CLEAN_BUILD = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
